### ISSUE TITLE
how to use href referenced in imageMaps.ts

### ISSUE THREAD

**Issue by kadaverik** [MakanaMakesStuff/Canvas-Image-Map#5]
Hi, i dived in your code but hasn't been able yet to determine how to use the hrefs referenced in the imageMaps.ts file, can you point me in the right direction ? thanks

**Comment by MakanaMakesStuff** [comment]
@kadaverik Sorry I didn't see this message until now. I am going to update the code as it's been a couple years and I'm sure I missed a lot, including the link feature you mentioned.

**Comment by MakanaMakesStuff** [comment]
@kadaverik Now it should handle both in app and external navigation. I forcefully pushed a new codebase to this repo so you may need to clone it again.
